version: '3.8'
services:

  postgres_user:
    image: postgres:15
    container_name: pg_user
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: userpass
      POSTGRES_DB: users_db
    ports:
      - "5433:5432"
    volumes:
      - pg_user_data:/var/lib/postgresql/data

  postgres_main:
    image: postgres:15
    container_name: pg_main
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: apppass
      POSTGRES_DB: pallet_db
    ports:
      - "5432:5432"
    volumes:
      - pg_main_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  # zookeeper:
  #   image: bitnami/zookeeper:3.9.2
  #   environment:
  #     - ALLOW_ANONYMOUS_LOGIN=yes
  #   ports:
  #     - "2181:2181"

  kafka:
    image: apache/kafka:3.7.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0


  scan-event-service:
    build: ./services/scan-event-service
    container_name: scan_event_service
    environment:
      - ConnectionStrings__Main=Host=postgres_main;Port=5432;Username=app;Password=apppass;Database=pallet_db
      - Kafka__BootstrapServers=kafka:9092
      - Redis__Connection=redis:6379
    ports:
      - "5001:80"
    depends_on:
      - postgres_main
      - kafka
      - redis

  route-analysis-service:
    build: ./services/route-analysis-service
    container_name: route_analysis_service
    environment:
      - ConnectionStrings__Main=Host=postgres_main;Port=5432;Username=app;Password=apppass;Database=pallet_db
      - Kafka__BootstrapServers=kafka:9092
    depends_on:
      - kafka
      - postgres_main

  deadtime-monitor:
    build: ./services/deadtime-monitor
    container_name: deadtime_monitor
    environment:
      - ConnectionStrings__Main=Host=postgres_main;Port=5432;Username=app;Password=apppass;Database=pallet_db
    depends_on:
      - postgres_main

  alert-service:
    build: ./services/alert-service
    container_name: alert_service
    environment:
      - ConnectionStrings__Alerts=Host=postgres_main;Port=5432;Username=app;Password=apppass;Database=pallet_db
      - Redis__Connection=redis:6379
    ports:
      - "5003:80"
    depends_on:
      - postgres_main
      - redis

volumes:
  pg_user_data:
  pg_main_data:
